Updates

diff --git a/English/functions/images-data/images-bullhead b/English/functions/images-data/images-bullhead
--- a/English/functions/images-data/images-bullhead
+++ b/English/functions/images-data/images-bullhead
@@ -1,84 +1,111 @@
 #!/bin/bash
 
-# Authors:
-#   Igor Dyatlov <dyatlov.igor@gmail.com>
-#
-# Copyright 2016 The Android Open Source Project
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#      http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
-
 function bullhead-MDB08M {
-  # Download
-  show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/bullhead-mdb08m-factory-5867cc27.tgz
-  # Extract
-  show_info 'Extraction Factory Images...'
-  tar zxf bullhead*.tgz
-  # Install
-  show_info 'Install Factory Images...'
-  cd bullhead-mdb08m
-  ./flash-all.sh
-  # Timeout
-  sleep 5
-  # Cleanup and finish
-  rm bullhead*.tgz
-  rm -rf bullhead*/
-  # Done
-  show_success 'Done.'
-  whiptail --title "Finished" --msgbox "Installation complete." 8 78
-  images
+MDB08M="bullhead-mdb08m-factory-5867cc27.tgz"
+  if [ -f "$MDB08M" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf bullhead*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd bullhead-mdb08m
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf bullhead*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/bullhead-mdb08m-factory-5867cc27.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf bullhead*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd bullhead-mdb08m
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf bullhead*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
 }
 
 function bullhead-MHC19Q {
-  # Download
-  show_info 'Download ...'
-  curl -O https://dl.google.com/dl/android/aosp/bullhead-mhc19q-factory-22ba5e5a.tgz
-  # Extract
-  show_info 'Extraction Factory Images...'
-  tar zxf bullhead*.tgz
-  # Install
-  show_info 'Install Factory Images...'
-  cd bullhead-mhc19q
-  ./flash-all.sh
-  # Timeout
-  sleep 5
-  # Cleanup and finish
-  rm bullhead*.tgz
-  rm -rf bullhead*/
-  # Done
-  show_success 'Done.'
-  whiptail --title "Finished" --msgbox "Installation complete." 8 78
-  images
+MHC19Q="bullhead-mhc19q-factory-22ba5e5a.tgz"
+  if [ -f "$MHC19Q" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf bullhead*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd bullhead-mhc19q
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf bullhead*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download ...'
+    wget https://dl.google.com/dl/android/aosp/bullhead-mhc19q-factory-22ba5e5a.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf bullhead*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd bullhead-mhc19q
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf bullhead*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
 }
 
 # Nexus 5X
 function images-bullhead {
-    eval `resize`
-    NEXUS5X=$(whiptail \
-        --notags \
-        --title "Nexus 5X" \
-        --menu "\nWhat is the firmware version you want to install?" \
-        --ok-button "Install" \
-        --cancel-button "Go Back" \
-        $LINES $COLUMNS $(( $LINES - 12 )) \
-        "bullhead-MDB08M"         "Marshmallow 6.0.0" \
-        "bullhead-MHC19Q"         "Marshmallow 6.0.1" \
-        3>&1 1>&2 2>&3)
+  eval `resize`
+  NEXUS5X=$(whiptail \
+    --notags \
+    --title 'Nexus 5X' \
+    --menu '\nWhat is the firmware version you want to install?' \
+    --ok-button 'Install' \
+    --cancel-button 'Go Back' \
+  $LINES $COLUMNS $(( $LINES - 12 )) \
+    bullhead-MDB08M 'Marshmallow 6.0.0' \
+    bullhead-MHC19Q 'Marshmallow 6.0.1' \
+  3>&1 1>&2 2>&3)
 
-    exitstatus=$?
-    if [ $exitstatus = 0 ]; then
-        clear && $NEXUS5X
-    else
-        clear && main
-    fi
+exitstatus=$?
+  if [ $exitstatus = 0 ]; then
+    clear && $NEXUS5X
+  else
+    clear && main
+  fi
 }
diff --git a/English/functions/images-data/images-hammerhead b/English/functions/images-data/images-hammerhead
--- a/English/functions/images-data/images-hammerhead
+++ b/English/functions/images-data/images-hammerhead
@@ -1,22 +1,5 @@
 #!/bin/bash
 
-# Authors:
-#   Igor Dyatlov <dyatlov.igor@gmail.com>
-#
-# Copyright 2016 The Android Open Source Project
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#      http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
-
 function hammerhead-KRT16M {
   # Download
   show_info 'Download Factory Images...'
@@ -28,6 +11,12 @@ function hammerhead-KRT16M {
   show_info 'Install Factory Images...'
   cd hammerhead-krt16m
   ./flash-all.sh
+  # Timeout
+  sleep 5
+  # Back
+  cd -
+  # Cleanup and finish
+  rm -rf hammerhead*
   # Done
   show_success 'Done.'
   whiptail --title "Finished" --msgbox "Installation complete." 8 78
@@ -45,6 +34,12 @@ function hammerhead-KTU84P {
   show_info 'Install Factory Images...'
   cd hammerhead-ktu84p
   ./flash-all.sh
+  # Timeout
+  sleep 5
+  # Back
+  cd -
+  # Cleanup and finish
+  rm -rf hammerhead*
   # Done
   show_success 'Done.'
   whiptail --title "Finished" --msgbox "Installation complete." 8 78
@@ -62,6 +57,12 @@ function hammerhead-LRX21O {
   show_info 'Install Factory Images...'
   cd hammerhead-lrx21o
   ./flash-all.sh
+  # Timeout
+  sleep 5
+  # Back
+  cd -
+  # Cleanup and finish
+  rm -rf hammerhead*
   # Done
   show_success 'Done.'
   whiptail --title "Finished" --msgbox "Installation complete." 8 78
@@ -71,7 +72,7 @@ function hammerhead-LRX21O {
 function hammerhead-LMY48M {
   # Download
   show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/hammerhead-lmy48m-factory-bf3c82fd.tgz
+  wget https://dl.google.com/dl/android/aosp/hammerhead-lmy48m-factory-bf3c82fd.tgz
   # Extract
   show_info 'Extraction Factory Images...'
   tar zxf hammerhead*.tgz
@@ -79,6 +80,12 @@ function hammerhead-LMY48M {
   show_info 'Install Factory Images...'
   cd hammerhead-lmy48m
   ./flash-all.sh
+  # Timeout
+  sleep 5
+  # Back
+  cd -
+  # Cleanup and finish
+  rm -rf hammerhead*
   # Done
   show_success 'Done.'
   whiptail --title "Finished" --msgbox "Installation complete." 8 78
@@ -88,7 +95,7 @@ function hammerhead-LMY48M {
 function hammerhead-MRA58N {
   # Download
   show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/hammerhead-mra58n-factory-aeca4139.tgz
+  wget https://dl.google.com/dl/android/aosp/hammerhead-mra58n-factory-aeca4139.tgz
   # Extract
   show_info 'Extraction Factory Images...'
   tar zxf hammerhead*.tgz
@@ -96,57 +103,84 @@ function hammerhead-MRA58N {
   show_info 'Install Factory Images...'
   cd hammerhead-mra58n
   ./flash-all.sh
+  # Timeout
+  sleep 5
+  # Back
+  cd -
+  # Cleanup and finish
+  rm -rf hammerhead*
   # Done
   show_success 'Done.'
   whiptail --title "Finished" --msgbox "Installation complete." 8 78
   images
 }
 
-function hammerhead-MOB30H {
-  # Download
-  show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/hammerhead-mob30h-factory-66d165e6.tgz
-  # Extract
-  show_info 'Extraction Factory Images...'
-  tar zxf hammerhead*.tgz
-  # Install
-  show_info 'Install Factory Images...'
-  cd hammerhead-mob30h
-  ./flash-all.sh
-  # Timeout
-  sleep 5
-  # Back
-  cd -
-  # Cleanup and finish
-  rm -rf hammerhead-mob30h*
-  # Done
-  show_success 'Done.'
-  whiptail --title "Finished" --msgbox "Installation complete." 8 78
-  images
+function hammerhead-MOB30P {
+MOB30P="hammerhead-mob30p-factory-6ceae57a.tgz"
+  if [ -f "$MOB30P" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf hammerhead*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd hammerhead-mob30p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf hammerhead*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/hammerhead-mob30p-factory-6ceae57a.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf hammerhead*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd hammerhead-mob30p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf hammerhead*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
 }
 
 # Nexus 5
 function images-hammerhead {
   eval `resize`
   NEXUS5=$(whiptail \
-      --notags \
-      --title "Nexus 5" \
-      --menu "\nWhat is the firmware version you want to install?" \
-      --ok-button "Install" \
-      --cancel-button "Go Back" \
-      $LINES $COLUMNS $(( $LINES - 12 )) \
-      "hammerhead-KRT16M"         "KitKat 4.4" \
-      "hammerhead-KTU84P"         "KitKat 4.4.4" \
-      "hammerhead-LRX21O"         "Lollipop 5.0" \
-      "hammerhead-LMY48M"         "Lollipop 5.1.1" \
-      "hammerhead-MRA58N"         "Marshmallow 6.0.0" \
-      "hammerhead-MOB30H"         "Marshmallow 6.0.1" \
-      3>&1 1>&2 2>&3)
+    --notags \
+    --title 'Nexus 5' \
+    --menu '\nWhat is the firmware version you want to install?' \
+    --ok-button 'Install' \
+    --cancel-button 'Go Back' \
+  $LINES $COLUMNS $(( $LINES - 12 )) \
+    hammerhead-KRT16M 'KitKat 4.4' \
+    hammerhead-KTU84P 'KitKat 4.4.4' \
+    hammerhead-LRX21O 'Lollipop 5.0' \
+    hammerhead-LMY48M 'Lollipop 5.1.1' \
+    hammerhead-MRA58N 'Marshmallow 6.0.0' \
+    hammerhead-MOB30P 'Marshmallow 6.0.1' \
+  3>&1 1>&2 2>&3)
 
-    exitstatus=$?
-    if [ $exitstatus = 0 ]; then
-        clear && $NEXUS5
-    else
-        clear && main
-    fi
+exitstatus=$?
+  if [ $exitstatus = 0 ]; then
+    clear && $NEXUS5
+  else
+    clear && main
+  fi
 }
