Updates

diff --git a/English/functions/images-data/images-fugu b/English/functions/images-data/images-fugu
--- a/English/functions/images-data/images-fugu
+++ b/English/functions/images-data/images-fugu
@@ -1,93 +1,210 @@
 #!/bin/bash
 
 function fugu-LRX21V {
-  # Download
-  show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/fugu-lrx21v-factory-64050f47.tgz
-  # Extract
-  show_info 'Extraction Factory Images...'
-  tar zxf fugu*.tgz
-  # Install
-  show_info 'Install Factory Images...'
-  cd fugu-lrx21v
-  ./flash-all.sh
-  # Done
-  show_success 'Done.'
-  whiptail --title "Finished" --msgbox "Installation complete." 8 78
-  images
+LRX21V="fugu-lrx21v-factory-64050f47.tgz"
+  if [ -f "$LRX21V" ]; then
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/fugu-lrx21v-factory-64050f47.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf fugu-lrx21v*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd fugu-lrx21v
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf fugu-lrx21v*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/fugu-lrx21v-factory-64050f47.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf fugu-lrx21v*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd fugu-lrx21v
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf fugu-lrx21v*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
 }
 
 function fugu-LMY48N {
-  # Download
-  show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/fugu-lmy48n-factory-3b9d8638.tgz
-  # Extract
-  show_info 'Extraction Factory Images...'
-  tar zxf fugu*.tgz
-  # Install
-  show_info 'Install Factory Images...'
-  cd fugu-lmy48n
-  ./flash-all.sh
-  # Done
-  show_success 'Done.'
-  whiptail --title "Finished" --msgbox "Installation complete." 8 78
-  images
+LMY48N="fugu-lmy48n-factory-3b9d8638.tgz"
+  if [ -f "$LMY48N" ]; then
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/fugu-lmy48n-factory-3b9d8638.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf fugu-lmy48n*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd fugu-lmy48n
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf fugu-lmy48n*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/fugu-lmy48n-factory-3b9d8638.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf fugu-lmy48n*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd fugu-lmy48n
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf fugu-lmy48n*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
 }
 
 function fugu-MRA58N {
-  # Download
-  show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/fugu-mra58n-factory-8517d819.tgz
-  # Extract
-  show_info 'Extraction Factory Images...'
-  tar zxf fugu*.tgz
-  # Install
-  show_info 'Install Factory Images...'
-  cd fugu-mra58n
-  ./flash-all.sh
-  # Done
-  show_success 'Done.'
-  whiptail --title "Finished" --msgbox "Installation complete." 8 78
-  images
+MRA58N="fugu-mra58n-factory-8517d819.tgz"
+  if [ -f "$MRA58N" ]; then
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/fugu-mra58n-factory-8517d819.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf fugu-mra58n*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd fugu-mra58n
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf fugu-mra58n*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/fugu-mra58n-factory-8517d819.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf fugu-mra58n*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd fugu-mra58n
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf fugu-mra58n*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
 }
 
-function fugu-MMB29V {
-  # Download
-  show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/fugu-mmb29v-factory-2db4c688.tgz
-  # Extract
-  show_info 'Extraction Factory Images...'
-  tar zxf fugu*.tgz
-  # Install
-  show_info 'Install Factory Images...'
-  cd fugu-mmb29v
-  ./flash-all.sh
-  # Done
-  show_success 'Done.'
-  whiptail --title "Finished" --msgbox "Installation complete." 8 78
-  images
+function fugu-MOB30P {
+MOB30P="fugu-mob30p-factory-08696c8b.tgz"
+  if [ -f "$MOB30P" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf fugu-mob30p*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd fugu-mob30p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf fugu-mob30p*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/fugu-mob30p-factory-08696c8b.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf fugu-mob30p*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd fugu-mob30p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf fugu-mob30p*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
 }
 
 # Nexus Player
 function images-fugu {
   eval `resize`
   NEXUSPLAY=$(whiptail \
-      --notags \
-      --title "Nexus Player" \
-      --menu "\nWhat is the firmware version you want to install?" \
-      --ok-button "Install" \
-      --cancel-button "Go Back" \
-      $LINES $COLUMNS $(( $LINES - 12 )) \
-      "fugu-LRX21V"         "Lollipop 5.0" \
-      "fugu-LMY48N"         "Lollipop 5.1.1" \
-      "fugu-MRA58N"         "Marshmallow 6.0.0" \
-      "fugu-MMB29V"         "Marshmallow 6.0.1" \
-      3>&1 1>&2 2>&3)
+    --notags \
+    --title 'Nexus Player' \
+    --menu '\nWhat is the firmware version you want to install?' \
+    --ok-button 'Install' \
+    --cancel-button 'Go Back' \
+  $LINES $COLUMNS $(( $LINES - 12 )) \
+    fugu-LRX21V 'Lollipop 5.0' \
+    fugu-LMY48N 'Lollipop 5.1.1' \
+    fugu-MRA58N 'Marshmallow 6.0' \
+    fugu-MOB30P 'Marshmallow 6.0.1' \
+  3>&1 1>&2 2>&3)
 
-    exitstatus=$?
-    if [ $exitstatus = 0 ]; then
-        clear && $NEXUSPLAY
-    else
-        clear && main
-    fi
+exitstatus=$?
+  if [ $exitstatus = 0 ]; then
+    clear && $NEXUSPLAY
+  else
+    clear && main
+  fi
 }
diff --git a/English/functions/images-data/images-mantaray b/English/functions/images-data/images-mantaray
--- a/English/functions/images-data/images-mantaray
+++ b/English/functions/images-data/images-mantaray
@@ -1,18 +1,291 @@
 #!/bin/bash
 
-# Authors:
-#   Igor Dyatlov <dyatlov.igor@gmail.com>
-#
-# Copyright 2016 The Android Open Source Project
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#      http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
+function mantaray-JDQ39 {
+JDQ39="mantaray-jdq39-factory-d79f489e.tgz"
+  if [ -f "$JDQ39" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf mantaray-jdq39*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd mantaray-jdq39
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf mantaray-jdq39*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/mantaray-jdq39-factory-d79f489e.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf mantaray-jdq39*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd mantaray-jdq39
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf mantaray-jdq39*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function mantaray-JWR66Y {
+JWR66Y="mantaray-jwr66y-factory-3d8252dd.tgz"
+  if [ -f "$JWR66Y" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf mantaray-jwr66y*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd mantaray-jwr66y
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf mantaray-jwr66y*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/mantaray-jwr66y-factory-3d8252dd.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-jwr66y*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-jwr66y
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-jwr66y*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function mantaray-KRT16S {
+KRT16S="mantaray-krt16s-factory-94413961.tgz"
+  if [ -f "$KRT16S" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf mantaray-krt16s*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd mantaray-krt16s
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf mantaray-krt16s*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/mantaray-krt16s-factory-94413961.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf mantaray-krt16s*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd mantaray-krt16s
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf mantaray-krt16s*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function mantaray-KTU84P {
+KTU84P="mantaray-ktu84p-factory-74e52998.tgz"
+  if [ -f "$KTU84P" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf mantaray-ktu84p*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd mantaray-ktu84p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf mantaray-ktu84p*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/mantaray-ktu84p-factory-74e52998.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-ktu84p*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-ktu84p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-ktu84p*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function mantaray-LRX21P {
+LRX21P="mantaray-lrx21p-factory-ad2499ea.tgz"
+  if [ -f "$LRX21P" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf mantaray-lrx21p*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd mantaray-lrx21p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf mantaray-lrx21p*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/mantaray-lrx21p-factory-ad2499ea.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf mantaray-lrx21p*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd mantaray-lrx21p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf mantaray-lrx21p*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function mantaray-LMY49J {
+LMY49J="mantaray-lmy49j-factory-7887b439.tgz"
+  if [ -f "$LMY49J" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-lmy49j*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-lmy49j
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-lmy49j*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/mantaray-lmy49j-factory-7887b439.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf mantaray-lmy49j*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd mantaray-lmy49j
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf mantaray-lmy49j*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+# Nexus 10
+function images-mantaray {
+  eval `resize`
+  NEXUS10=$(whiptail \
+    --notags \
+    --title 'Nexus 10' \
+    --menu '\nWhat is the firmware version you want to install?' \
+    --ok-button 'Install' \
+    --cancel-button 'Go Back' \
+  $LINES $COLUMNS $(( $LINES - 12 )) \
+    mantaray-JDQ39 'Jelly Bean 4.2.2' \
+    mantaray-JWR66Y 'Jelly Bean 4.3' \
+    mantaray-KRT16S 'KitKat 4.4' \
+    mantaray-KTU84P 'KitKat 4.4.4' \
+    mantaray-LRX21PLRX21P 'Lollipop 5.0' \
+    mantaray-LMY49J 'Lollipop 5.1.1' \
+  3>&1 1>&2 2>&3)
+
+exitstatus=$?
+  if [ $exitstatus = 0 ]; then
+    clear && $NEXUS10
+  else
+    clear && main
+  fi
+}
diff --git a/English/functions/images-data/images-occam b/English/functions/images-data/images-occam
--- a/English/functions/images-data/images-occam
+++ b/English/functions/images-data/images-occam
@@ -1,18 +1,291 @@
 #!/bin/bash
 
-# Authors:
-#   Igor Dyatlov <dyatlov.igor@gmail.com>
-#
-# Copyright 2016 The Android Open Source Project
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#      http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
+function occam-JDQ39 {
+JDQ39="occam-jdq39-factory-345dc199.tgz"
+  if [ -f "$JDQ39" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-jdq39*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-jdq39
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-jdq39*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/occam-jdq39-factory-345dc199.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-jdq39*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-jdq39
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-jdq39*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function occam-JWR66Y {
+JWR66Y="occam-jwr66y-factory-74b1deab.tgz"
+  if [ -f "$JWR66Y" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-jwr66y*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-jwr66y
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-jwr66y*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/occam-jwr66y-factory-74b1deab.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-jwr66y*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-jwr66y
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-jwr66y*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function occam-KRT16S {
+KRT16S="occam-krt16s-factory-2006f418.tgz"
+  if [ -f "$KRT16S" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-krt16s*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-krt16s
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-krt16s*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/occam-krt16s-factory-2006f418.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-krt16s*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-krt16s
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-krt16s*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function occam-KTU84P {
+KTU84P="occam-ktu84p-factory-b6ac3ad6.tgz"
+  if [ -f "$KTU84P" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-ktu84p*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-ktu84p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-ktu84p*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/occam-ktu84p-factory-b6ac3ad6.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-ktu84p*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-ktu84p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-ktu84p*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function occam-LRX21T {
+LRX21T="occam-lrx21t-factory-51cee750.tgz"
+  if [ -f "$LRX21T" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-lrx21t*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-lrx21t
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-lrx21t*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/occam-lrx21t-factory-51cee750.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-lrx21t*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-lrx21t
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-lrx21t*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function occam-LMY48T {
+LMY48T="occam-lmy48t-factory-416938f1.tgz"
+  if [ -f "$LMY48T" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-lmy48t*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-lmy48t
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-lmy48t*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/occam-lmy48t-factory-416938f1.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf occam-lmy48t*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd occam-lmy48t
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf occam-lmy48t*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+# Nexus 4
+function images-occam {
+  eval `resize`
+  NEXUS4=$(whiptail \
+    --notags \
+    --title 'Nexus 4' \
+    --menu '\nWhat is the firmware version you want to install?' \
+    --ok-button 'Install' \
+    --cancel-button 'Go Back' \
+  $LINES $COLUMNS $(( $LINES - 12 )) \
+    occam-JDQ39 'Jelly Bean 4.2.2' \
+    occam-JWR66Y 'Jelly Bean 4.3' \
+    occam-KRT16S 'KitKat 4.4' \
+    occam-KTU84P 'KitKat 4.4.4' \
+    occam-LRX21T 'Lollipop 5.0' \
+    occam-LMY48T 'Lollipop 5.1.1' \
+  3>&1 1>&2 2>&3)
+
+exitstatus=$?
+  if [ $exitstatus = 0 ]; then
+    clear && $NEXUS4
+  else
+    clear && main
+  fi
+}
diff --git a/English/functions/images-data/images-razorg b/English/functions/images-data/images-razorg
--- a/English/functions/images-data/images-razorg
+++ b/English/functions/images-data/images-razorg
@@ -1,18 +1,381 @@
 #!/bin/bash
 
-# Authors:
-#   Igor Dyatlov <dyatlov.igor@gmail.com>
-#
-# Copyright 2016 The Android Open Source Project
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#      http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
+function razor-JSS15R {
+JSS15R="razor-jss15r-factory-ec2d4f76.tgz"
+  if [ -f "$JSS15R" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razor-jss15r*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razor-jss15r
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razor-jss15r*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/razor-jss15r-factory-ec2d4f76.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razor-jss15r*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razor-jss15r
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razor-jss15r*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function razor-KRT16S {
+KRT16S="razor-krt16s-factory-7235eb0d.tgz"
+  if [ -f "$KRT16S" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razor*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razor-krt16s
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razor-*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/razor-krt16s-factory-7235eb0d.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razor*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razor-krt16s
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razor-*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function razor-KTU84P {
+KTU84P="razor-ktu84p-factory-b1b2c0da.tgz"
+  if [ -f "$KTU84P" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razor*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razor-ktu84p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razor-*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/razor-ktu84p-factory-b1b2c0da.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razor*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razor-ktu84p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razor-*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function razor-LRX21P {
+LRX21P="razor-lrx21p-factory-ba55c6ab.tgz"
+  if [ -f "$LRX21P" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razor*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razor-lrx21p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razor-*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/razor-lrx21p-factory-ba55c6ab.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razor*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razor-lrx21p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razor-*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function razor-LRX22G {
+LRX22G="razor-lrx22g-factory-bff2093e.tgz"
+  if [ -f "$LRX22G" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razor-lrx22g*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razor-lrx22g
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razor-lrx22g*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/razor-lrx22g-factory-bff2093e.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razor-lrx22g*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razor-lrx22g
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razor-lrx22g*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function razor-LMY48T {
+LMY48T="razor-lmy48t-factory-b6a844f2.tgz"
+  if [ -f "$LMY48T" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razor-lmy48t*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razor-lmy48t
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razor-lmy48t*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/razor-lmy48t-factory-b6a844f2.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razor-lmy48t*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razor-lmy48t
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razor-lmy48t*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function razorg-MRA59B {
+MRA59B="razorg-mra59b-factory-088505a6.tgz"
+  if [ -f "$MRA59B" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razorg-mra59b*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razorg-mra59b
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razorg-mra59b*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/razorg-mra59b-factory-088505a6.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razorg-mra59b*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razorg-mra59b
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razorg-mra59b*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function razorg-MOB30P {
+MOB30P="razorg-mob30p-factory-2c47d822.tgz"
+  if [ -f "$MOB30P" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razorg-mob30p*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razorg-mob30p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razorg-mob30p*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/razorg-mob30p-factory-2c47d822.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf razorg-mob30p*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd razorg-mob30p
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf razorg-mob30p*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+# Nexus 7
+function images-razorg {
+  eval `resize`
+  NEXUS7M=$(whiptail \
+    --notags \
+    --title 'Nexus 7 [2013] (Mobile)' \
+    --menu '\nWhat is the firmware version you want to install?' \
+    --ok-button 'Install' \
+    --cancel-button 'Go Back' \
+  $LINES $COLUMNS $(( $LINES - 12 )) \
+    razorg-JSS15R 'Jelly Bean 4.3' \
+    razorg-KRT16S 'KitKat 4.4' \
+    razorg-KTU84P 'KitKat 4.4.4' \
+    razorg-LRX21P 'Lollipop 5.0' \
+    razorg-LRX22G 'Lollipop 5.0.2' \
+    razorg-LMY48T 'Lollipop 5.1.1' \
+    razorg-MRA59B 'Marshmallow 6.0' \
+    razorg-MOB30P 'Marshmallow 6.0.1' \
+  3>&1 1>&2 2>&3)
+
+exitstatus=$?
+  if [ $exitstatus = 0 ]; then
+    clear && $NEXUS7M
+  else
+    clear && main
+  fi
+}
diff --git a/English/functions/images-data/images-yakju b/English/functions/images-data/images-yakju
--- a/English/functions/images-data/images-yakju
+++ b/English/functions/images-data/images-yakju
@@ -1,56 +1,201 @@
 #!/bin/bash
 
-# Authors:
-#   Igor Dyatlov <dyatlov.igor@gmail.com>
-#
-# Copyright 2016 The Android Open Source Project
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#      http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
-
-function - {
-  # Download
-  show_info 'Download Factory Images...'
-  curl -O
-  # Extract
-  show_info 'Extraction Factory Images...'
-  tar zxf *.tgz
-  # Install
-  show_info 'Install Factory Images...'
-  cd -
-  ./flash-all.sh
-  # Done
-  show_success 'Done.'
-  whiptail --title "Finished" --msgbox "Installation complete." 8 78
-  images
+function yakju-IMM76I {
+IMM76I="yakju-imm76i-factory-8001e72f.tgz"
+  if [ -f "$IMM76I" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf yakju-imm76i*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd yakju-imm76i
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf yakju-imm76i*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/yakju-imm76i-factory-8001e72f.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf yakju-imm76i*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd yakju-imm76i
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf yakju-imm76i*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
 }
 
-#
-function images- {
-  eval `resize`
-  =$(whiptail \
-      --notags \
-      --title " " \
-      --menu "\nFor what device you want to flash the recovery?" \
-      --ok-button "Install" \
-      --cancel-button "Go Back" \
-      $LINES $COLUMNS $(( $LINES - 12 )) \
-      "yakju-"         " " \
-      3>&1 1>&2 2>&3)
+function yakju-JZO54K {
+JZO54K="occam-ktu84p-factory-b6ac3ad6.tgz"
+  if [ -f "$JZO54K" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf yakju-jzo54k*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd yakju-jzo54k
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf yakju-jzo54k*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/yakju-jzo54k-factory-92ff9457.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf yakju-jzo54k*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd yakju-jzo54k
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf yakju-jzo54k*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
 
-    exitstatus=$?
-    if [ $exitstatus = 0 ]; then
-        clear && $
-    else
-        clear && main
-    fi
+function yakju-JDQ39 {
+JDQ39="yakju-jdq39-factory-b2ebb5f3.tgz"
+  if [ -f "$JDQ39" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf yakju-jdq39*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd yakju-jdq39
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf yakju-jdq39*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/yakju-jdq39-factory-b2ebb5f3.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf yakju-jdq39*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd yakju-jdq39
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf yakju-jdq39*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+function yakju-JWR66Y {
+JWR66Y="yakju-jwr66y-factory-09207065.tgz"
+  if [ -f "$JWR66Y" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf yakju-jwr66y*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd yakju-jwr66y
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf yakju-jwr66y*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/yakju-jwr66y-factory-09207065.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf yakju-jwr66y*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd yakju-jwr66y
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf yakju-jwr66y*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
+}
+
+# Galaxy Nexus (GSM/HSPA+)
+function images-yakju {
+  eval `resize`
+  NEXUS3=$(whiptail \
+    --notags \
+    --title 'Galaxy Nexus (GSM/HSPA+)' \
+    --menu '\nWhat is the firmware version you want to install?' \
+    --ok-button 'Install' \
+    --cancel-button 'Go Back' \
+  $LINES $COLUMNS $(( $LINES - 12 )) \
+    yakju-IMM76I 'Ice Cream Sandwich 4.0.4 ' \
+    yakju-JZO54K 'Jelly Bean 4.1.2 ' \
+    yakju-JDQ39 'Jelly Bean 4.2.2 ' \
+    yakju-JWR66Y 'Jelly Bean 4.3' \
+  3>&1 1>&2 2>&3)
+
+exitstatus=$?
+  if [ $exitstatus = 0 ]; then
+    clear && $NEXUS3
+  else
+    clear && main
+  fi
 }
