Replacement function curl and enter the verification firmware images if they are already in the folder

diff --git a/English/functions/images-data/images-angler b/English/functions/images-data/images-angler
--- a/English/functions/images-data/images-angler
+++ b/English/functions/images-data/images-angler
@@ -1,84 +1,111 @@
 #!/bin/bash
 
-# Authors:
-#   Igor Dyatlov <dyatlov.igor@gmail.com>
-#
-# Copyright 2016 The Android Open Source Project
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#      http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
-
 function angler-MMB29N {
-  # Download
-  show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/angler-mmb29n-factory-b1463752.tgz
-  # Extract
-  show_info 'Extraction Factory Images...'
-  tar zxf angler*.tgz
-  # Install
-  show_info 'Install Factory Images...'
-  cd angler-mmb29n
-  ./flash-all.sh
-  # Timeout
-  sleep 5
-  # Cleanup and finish
-  rm angler*.tgz
-  rm -rf angler*/
-  # Done
-  show_success 'Done.'
-  whiptail --title "Finished" --msgbox "Installation complete." 8 78
-  images
+MMB29N="angler-mmb29n-factory-b1463752.tgz"
+  if [ -f "$MMB29N" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf angler*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd angler-mmb29n
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf angler*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/angler-mmb29n-factory-b1463752.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf angler*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd angler-mmb29n
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf angler*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
 }
 
-function angler-MHC19Q {
-  # Download
-  show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/angler-mhc19q-factory-f5a4e7a1.tgz
-  # Extract
-  show_info 'Extraction Factory Images...'
-  tar zxf angler*.tgz
-  # Install
-  show_info 'Install Factory Images...'
-  cd angler-mhc19q
-  ./flash-all.sh
-  # Timeout
-  sleep 5
-  # Cleanup and finish
-  rm angler*.tgz
-  rm -rf angler*/
-  # Done
-  show_success 'Done.'
-  whiptail --title "Finished" --msgbox "Installation complete." 8 78
-  images
+function angler-MTC19X {
+MTC19X="angler-mtc19x-factory-83a34810.tgz"
+  if [ -f "$MTC19X" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf angler*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd angler-mhc19q
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf angler*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/angler-mtc19x-factory-83a34810.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf angler*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd angler-mhc19q
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf angler*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
 }
 
 # Nexus 6P
 function images-angler {
   eval `resize`
   NEXUS6P=$(whiptail \
-      --notags \
-      --title "Nexus 6P" \
-      --menu "\nWhat is the firmware version you want to install?" \
-      --ok-button "Install" \
-      --cancel-button "Go Back" \
-      $LINES $COLUMNS $(( $LINES - 12 )) \
-      angler-MMB29N "Marshmallow 6.0.0" \
-      angler-MHC19Q "Marshmallow 6.0.1" \
-      3>&1 1>&2 2>&3)
+    --notags \
+    --title 'Nexus 6P' \
+    --menu '\nWhat is the firmware version you want to install?' \
+    --ok-button 'Install' \
+    --cancel-button 'Go Back' \
+  $LINES $COLUMNS $(( $LINES - 12 )) \
+    angler-MMB29N 'Marshmallow 6.0.0' \
+    angler-MTC19X 'Marshmallow 6.0.1' \
+  3>&1 1>&2 2>&3)
 
-    exitstatus=$?
-    if [ $exitstatus = 0 ]; then
-        clear && $NEXUS6P
-    else
-        clear && main
-    fi
+exitstatus=$?
+  if [ $exitstatus = 0 ]; then
+    clear && $NEXUS6P
+  else
+    clear && main
+  fi
 }
diff --git a/English/functions/images-data/images-ryu b/English/functions/images-data/images-ryu
--- a/English/functions/images-data/images-ryu
+++ b/English/functions/images-data/images-ryu
@@ -1,56 +1,66 @@
 #!/bin/bash
 
-# Authors:
-#   Igor Dyatlov <dyatlov.igor@gmail.com>
-#
-# Copyright 2016 The Android Open Source Project
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#      http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
-
-function ryu-MXC14G {
-  # Download
-  show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/ryu-mxc14g-factory-3bc18b89.tgz
-  # Extract
-  show_info 'Extraction Factory Images...'
-  tar zxf ryu*.tgz
-  # Install
-  show_info 'Install Factory Images...'
-  cd ryu-mxc14g
-  ./flash-all.sh
-  # Done
-  show_success 'Done.'
-  whiptail --title "Finished" --msgbox "Installation complete." 8 78
-  images
+function ryu-MXC89H {
+MXC89H="ryu-mxc89h-factory-f4c33d9c.tgz"
+  if [ -f "$MXC89H" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf ryu*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd ryu-mxc14g
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf ryu*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/ryu-mxc89h-factory-f4c33d9c.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf ryu*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd ryu-mxc14g
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf ryu*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
 }
 
 # Pixel C
 function images-ryu {
   eval `resize`
   NEXUS5X=$(whiptail \
-      --notags \
-      --title "Pixel C" \
-      --menu "\nWhat is the firmware version you want to install?" \
-      --ok-button "Install" \
-      --cancel-button "Go Back" \
-      $LINES $COLUMNS $(( $LINES - 12 )) \
-       "ryu-MXC14G"         "Marshmallow 6.0.1" \
-      3>&1 1>&2 2>&3)
+    --notags \
+    --title 'Pixel C' \
+    --menu '\nWhat is the firmware version you want to install?' \
+    --ok-button 'Install' \
+    --cancel-button 'Go Back' \
+  $LINES $COLUMNS $(( $LINES - 12 )) \
+    ryu-MXC89H 'Marshmallow 6.0.1' \
+  3>&1 1>&2 2>&3)
 
-    exitstatus=$?
-    if [ $exitstatus = 0 ]; then
-        clear && $PIXELC
-    else
-        clear && main
-    fi
+exitstatus=$?
+  if [ $exitstatus = 0 ]; then
+    clear && $PIXELC
+  else
+    clear && main
+  fi
 }
diff --git a/English/functions/images-data/images-shamu b/English/functions/images-data/images-shamu
--- a/English/functions/images-data/images-shamu
+++ b/English/functions/images-data/images-shamu
@@ -3,7 +3,7 @@
 function shamu-LRX21O {
   # Download
   show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/shamu-lrx21o-factory-e028f5ea.tgz
+  wget https://dl.google.com/dl/android/aosp/shamu-lrx21o-factory-e028f5ea.tgz
   # Extract
   show_info 'Extraction Factory Images...'
   tar zxf shamu*.tgz
@@ -11,6 +11,12 @@ function shamu-LRX21O {
   show_info 'Install Factory Images...'
   cd shamu-lrx21o
   ./flash-all.sh
+  # Timeout
+  sleep 5
+  # Back
+  cd -
+  # Cleanup and finish
+  rm -rf shamu*
   # Done
   show_success 'Done.'
   whiptail --title "Finished" --msgbox "Installation complete." 8 78
@@ -20,7 +26,7 @@ function shamu-LRX21O {
 function shamu-LRX22C {
   # Download
   show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/shamu-lrx22c-factory-ff173fc6.tgz
+  wget https://dl.google.com/dl/android/aosp/shamu-lrx22c-factory-ff173fc6.tgz
   # Extract
   show_info 'Extraction Factory Images...'
   tar zxf shamu*.tgz
@@ -28,6 +34,12 @@ function shamu-LRX22C {
   show_info 'Install Factory Images...'
   cd shamu-lrx22c
   ./flash-all.sh
+  # Timeout
+  sleep 5
+  # Back
+  cd -
+  # Cleanup and finish
+  rm -rf shamu*
   # Done
   show_success 'Done.'
   whiptail --title "Finished" --msgbox "Installation complete." 8 78
@@ -37,7 +49,7 @@ function shamu-LRX22C {
 function shamu-LMY47I {
   # Download
   show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/shamu-lmy47i-factory-c8afc588.tgz
+  wget https://dl.google.com/dl/android/aosp/shamu-lmy47i-factory-c8afc588.tgz
   # Extract
   show_info 'Extraction Factory Images...'
   tar zxf shamu*.tgz
@@ -45,6 +57,12 @@ function shamu-LMY47I {
   show_info 'Install Factory Images...'
   cd shamu-lmy47i
   ./flash-all.sh
+  # Timeout
+  sleep 5
+  # Back
+  cd -
+  # Cleanup and finish
+  rm -rf shamu*
   # Done
   show_success 'Done.'
   whiptail --title "Finished" --msgbox "Installation complete." 8 78
@@ -54,7 +72,7 @@ function shamu-LMY47I {
 function shamu-LMY48Y {
   # Download
   show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/shamu-lmy48y-factory-df0504a8.tgz
+  wget https://dl.google.com/dl/android/aosp/shamu-lmy48y-factory-df0504a8.tgz
   # Extract
   show_info 'Extraction Factory Images...'
   tar zxf shamu*.tgz
@@ -62,6 +80,12 @@ function shamu-LMY48Y {
   show_info 'Install Factory Images...'
   cd shamu-lmy48y
   ./flash-all.sh
+  # Timeout
+  sleep 5
+  # Back
+  cd -
+  # Cleanup and finish
+  rm -rf shamu*
   # Done
   show_success 'Done.'
   whiptail --title "Finished" --msgbox "Installation complete." 8 78
@@ -71,7 +95,7 @@ function shamu-LMY48Y {
 function shamu-MRA58X {
   # Download
   show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/shamu-mra58x-factory-7ddc0948.tgz
+  wget https://dl.google.com/dl/android/aosp/shamu-mra58x-factory-7ddc0948.tgz
   # Extract
   show_info 'Extraction Factory Images...'
   tar zxf shamu*.tgz
@@ -79,51 +103,84 @@ function shamu-MRA58X {
   show_info 'Install Factory Images...'
   cd shamu-mra58x
   ./flash-all.sh
+  # Timeout
+  sleep 5
+  # Back
+  cd -
+  # Cleanup and finish
+  rm -rf shamu*
   # Done
   show_success 'Done.'
   whiptail --title "Finished" --msgbox "Installation complete." 8 78
   images
 }
 
-function shamu-MMB29X {
-  # Download
-  show_info 'Download Factory Images...'
-  curl -O https://dl.google.com/dl/android/aosp/shamu-mmb29x-factory-ef4cbb75.tgz
-  # Extract
-  show_info 'Extraction Factory Images...'
-  tar zxf shamu*.tgz
-  # Install
-  show_info 'Install Factory Images...'
-  cd shamu-mmb29x
-  ./flash-all.sh
-  # Done
-  show_success 'Done.'
-  whiptail --title "Finished" --msgbox "Installation complete." 8 78
-  images
+function shamu-MOB30O {
+MOB30O="shamu-mob30o-factory-e90fd025.tgz"
+  if [ -f "$MOB30O" ]; then
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf shamu*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd shamu-mob30o
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf shamu*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  else
+    # Download
+    show_info 'Download Factory Images...'
+    wget https://dl.google.com/dl/android/aosp/shamu-mob30o-factory-e90fd025.tgz
+    # Extract
+    show_info 'Extraction Factory Images...'
+    tar zxf shamu*.tgz
+    # Install
+    show_info 'Install Factory Images...'
+    cd shamu-mob30o
+    ./flash-all.sh
+    # Timeout
+    sleep 5
+    # Back
+    cd -
+    # Cleanup and finish
+    rm -rf shamu*
+    # Done
+    show_success 'Done.'
+    whiptail --title "Finished" --msgbox "Installation complete." 8 78
+    images
+  fi
 }
 
 # Nexus 6
 function images-shamu {
-eval `resize`
-NEXUS6=$(whiptail \
---notags \
---title "Nexus 6" \
---menu "\nWhat is the firmware version you want to install?" \
---ok-button "Install" \
---cancel-button "Go Back" \
-$LINES $COLUMNS $(( $LINES - 12 )) \
-shamu-LRX21O 'Lollipop 5.0.0' \
-shamu-LRX22C 'Lollipop 5.0.1' \
-shamu-LMY47I 'Lollipop 5.1.0' \
-shamu-LMY48Y 'Lollipop 5.1.1' \
-shamu-MRA58X 'Marshmallow 6.0.0' \
-shamu-MMB29X 'Marshmallow 6.0.1' \
-3>&1 1>&2 2>&3)
+  eval `resize`
+  NEXUS6=$(whiptail \
+    --notags \
+    --title "Nexus 6" \
+    --menu "\nWhat is the firmware version you want to install?" \
+    --ok-button "Install" \
+    --cancel-button "Go Back" \
+  $LINES $COLUMNS $(( $LINES - 12 )) \
+    shamu-LRX21O 'Lollipop 5.0.0' \
+    shamu-LRX22C 'Lollipop 5.0.1' \
+    shamu-LMY47I 'Lollipop 5.1.0' \
+    shamu-LMY48Y 'Lollipop 5.1.1' \
+    shamu-MRA58X 'Marshmallow 6.0.0' \
+    shamu-MOB30O 'Marshmallow 6.0.1' \
+  3>&1 1>&2 2>&3)
 
 exitstatus=$?
-if [ $exitstatus = 0 ]; then
-clear && $NEXUS6
-else
-clear && main
-fi
+  if [ $exitstatus = 0 ]; then
+    clear && $NEXUS6
+  else
+    clear && main
+  fi
 }
